Fix building with Visual Studio (snprintf)
This commit is an addition to 4b9e9b1d28ea7eaec44ff73e2f91c4064986b12a

Building with Visual Studio breaks as snprintf is not implemented:
  vdagent\file_xfer.cpp(198) : error C3861: 'snprintf': identifier not found

Replace it with sprintf_s for Visual Studio.

Trying to use sprintf_s for both Visual Studio and mingw
failed for mingw64 (build succeeds but runtime error appears).